// Hand-authored monochrome pixel-art icons for the retro "boutique" skin.
// Each icon is an ASCII grid ('#' = filled, '.' = transparent) compiled to a
// crisp SVG <symbol> that fills with `currentColor` — so a single set recolours
// with the theme (brass at rest, teal when live). Vector, so it stays sharp at
// any size when paired with `image-rendering: pixelated`.
//
// To add/edit an icon, change its grid below. Keep rows equal length.

export type PixelIconName =
  | "flame"
  | "link"
  | "bolt"
  | "eyeoff"
  | "trophy"
  | "target"
  | "swap"
  | "ball"
  | "gear"
  | "star";

const ICONS: Record<PixelIconName, string> = {
  flame: `
.......#........
.......##.......
......###.......
......####......
.....##.##......
.....#..###.....
....##...##.....
....#.....##....
...##..#...##...
...#..###..##...
...#..###...#...
...##.###..##...
....#......#....
....##....##....
.....######.....
......####......`,
  link: `
.#####..........
#.....#.........
#.....#.........
#.....#.........
#.....#.........
.#####.#####....
......#.....#...
......#.....#...
......#.....#...
......#.....#...
.......#####....
................`,
  bolt: `
........###.....
.......###......
......###.......
.....###........
....#######......
...#######.......
......###........
.....###.........
....###..........
...###...........
..###............`,
  eyeoff: `
................
....########....
..##........##..
.#............#.
#..............#
................
..#....#....#...
..#....#....#...`,
  trophy: `
.############...
.#..........#...
##.########.##..
#..########..#..
#..########..#..
.#.########.#...
.##.######.##...
..##......##....
....######......
......####......
......####......
.....######.....
....########....
...##########...`,
  target: `
....########....
..##........##..
.#....####....#.
#....######....#
#...##....##...#
#..##..##..##..#
#..#..####..#..#
#..#..####..#..#
#..##..##..##..#
#...##....##...#
#....######....#
.#....####....#.
..##........##..
....########....`,
  swap: `
.....##.....
....####....
...######...
..########..
.##########.
.....##.....
.....##.....
.##########.
..########..
...######...
....####....
.....##.....`,
  ball: `
....######....
..##......##..
.#....##....#.
#....####....#
#...##..##...#
#..##....##..#
#..#......#..#
#..##....##..#
#...##..##...#
.#....##....#.
..##......##..
....######....`,
  gear: `
......####......
......####......
....########....
...##########...
..############..
..############..
######....######
######....######
######....######
######....######
..############..
..############..
...##########...
....########....
......####......
......####......`,
  star: `
......#......
......#......
.....###.....
.....###.....
....#####....
#############
.###########.
..#########..
...#######...
...##.#.##...
..##.....##..
.##.......##.`,
};

/** Rects for one grid, merged into horizontal runs to keep the DOM small. */
function gridRects(grid: string): { rects: string; w: number; h: number } {
  const rows = grid.trim().split("\n");
  const h = rows.length;
  const w = Math.max(...rows.map((r) => r.length));
  let rects = "";
  rows.forEach((row, y) => {
    let x = 0;
    while (x < row.length) {
      if (row[x] === "#") {
        let run = 1;
        while (row[x + run] === "#") run++;
        rects += `<rect x="${x}" y="${y}" width="${run}" height="1"/>`;
        x += run;
      } else {
        x++;
      }
    }
  });
  return { rects, w, h };
}

/**
 * One-time sprite of every icon as a hidden <symbol> set. Mount once near the
 * app root; individual <PixelIcon> instances reference these by id.
 */
export function PixelIconSprite() {
  return (
    <svg
      aria-hidden="true"
      style={{ position: "absolute", width: 0, height: 0, overflow: "hidden" }}
    >
      {(Object.keys(ICONS) as PixelIconName[]).map((name) => {
        const { rects, w, h } = gridRects(ICONS[name]);
        return (
          <symbol
            key={name}
            id={`pix-${name}`}
            viewBox={`0 0 ${w} ${h}`}
            fill="currentColor"
            dangerouslySetInnerHTML={{ __html: rects }}
          />
        );
      })}
    </svg>
  );
}

/** A single pixel icon. Colour follows `currentColor`; size via `size` (px). */
export function PixelIcon({
  name,
  size = 18,
  className = "",
}: {
  name: PixelIconName;
  size?: number;
  className?: string;
}) {
  return (
    <svg
      width={size}
      height={size}
      className={className}
      style={{ imageRendering: "pixelated", display: "block" }}
      aria-hidden="true"
    >
      <use href={`#pix-${name}`} />
    </svg>
  );
}
